Repository LukeErdy/CS-320-Project, pull requests merged in 2024-03, with the labels that each got.

#69 Fixed some bugs and added more data collection
  .DS_Store
  Demo/.DS_Store
  Demo/Assets/.DS_Store
  Demo/Assets/DataConsent.cs
  Demo/Assets/DataConsent.cs.meta
  Demo/Assets/Enemy.cs
  Demo/Assets/GameSession.cs
  Demo/Assets/Player.cs
  Demo/Assets/Scenes/.DS_Store
  Demo/Assets/Scenes/Data Collection.unity
  Demo/Assets/Scenes/Main Menu.unity
  Demo/Assets/Scenes/SampleScene.unity
Labels: bug, enhancement

#70 Put EnemySpawn script back into Grid
  Demo/Assets/Scenes/SampleScene.unity
Labels: bug

#71 amy/snake enemy
  Demo/Assets/Actor.cs
  Demo/Assets/Characters/Snake.prefab
  Demo/Assets/Characters/Snake.prefab.meta
  Demo/Assets/Characters/SnakeAttack.png
  Demo/Assets/Characters/SnakeAttack.png.meta
  Demo/Assets/Characters/SnakeIdle.png
  Demo/Assets/Characters/SnakeIdle.png.meta
  Demo/Assets/Enemy.cs
  Demo/Assets/EnemySpawn.cs
  Demo/Assets/Player.cs
  Demo/Assets/Scenes/SampleScene.unity
Labels: enhancement

#72 Got Unity Test Folder setup
  Demo/Assets/Tests.meta
  Demo/Assets/Tests/AmysTest.cs
  Demo/Assets/Tests/AmysTest.cs.meta
  Demo/Assets/Tests/Tests.asmdef
  Demo/Assets/Tests/Tests.asmdef.meta
  Demo/ProjectSettings/TimelineSettings.asset
Labels: enhancement

#76 Add testing to branch
  Demo/Assets/Scenes/SampleScene.unity
  Demo/Assets/Scripts/ChatBar.cs
  Demo/Assets/Scripts/ChatBar.cs.meta
  Demo/Assets/Scripts/ChatBox.cs
  Demo/Assets/Scripts/ChatBox.cs.meta
  Demo/Assets/Scripts/Message.cs
  Demo/Assets/Scripts/Message.cs.meta
  Demo/Assets/Scripts/OnlineOnKey.cs
  Demo/Assets/Scripts/OpenChatBox.cs
  Demo/Assets/Tests/GrantsTest.cs
  Demo/Assets/Tests/GrantsTest.cs.meta
Labels: documentation

#79 Started working on cave generation
  Demo/Assets/Scripts/Generate.cs
  Demo/Assets/Tests/CalebsTests.cs
Labels: enhancement

#80 FIREBALL!
  Demo/Assets/Resources/Fire.png
  Demo/Assets/Resources/Fire.png.meta
  Demo/Assets/Resources/Fireball.prefab
  Demo/Assets/Resources/Fireball.prefab.meta
  Demo/Assets/Resources/Rodent.prefab
  Demo/Assets/Resources/Snake.prefab
  Demo/Assets/Scenes/SampleScene.unity
  Demo/Assets/Scripts/Actor.cs
  Demo/Assets/Scripts/ChatFollowPlayer.cs
  Demo/Assets/Scripts/Enemy.cs
  Demo/Assets/Scripts/ManaMeter.cs
  Demo/Assets/Scripts/ManaMeter.cs.meta
  Demo/Assets/Scripts/Player.cs
  Demo/Assets/Scripts/Projectile.cs
  Demo/Assets/Scripts/Projectile.cs.meta
  Demo/Assets/Tests/AmysTest.cs
Labels: enhancement

#81 Created GameSession Prefab
  Demo/Assets/.DS_Store
  Demo/Assets/Resources/GameSession.prefab
  Demo/Assets/Resources/GameSession.prefab.meta
  Demo/Assets/Scenes/Main Menu.unity
  Demo/Assets/Scripts/Enemy.cs
  Demo/Assets/Scripts/GameSession.cs
  Demo/Assets/Scripts/Player.cs
  Demo/Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Electronic Highway Sign SDF.asset
Labels: bug

#84 Kept Working on Cave Generation
  Demo/Assets/Scripts/Enemy.cs
  Demo/Assets/Scripts/EnemySpawn.cs
  Demo/Assets/Scripts/Generate.cs
Labels: enhancement
